name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@main

      - name: Set up repository
        uses: actions/checkout@main
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Run repository-wide tests
        if: runner.os == 'Linux'
        working-directory:  ${{ github.workspace }}/.github
        run: ./run-checks.sh

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx

      - name: Build and check with Gradle
        run: ./gradlew check coverage --info

      - name: Upload tests artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'test-report-${{ matrix.platform }}'
          path: 'build/reports/tests/test'

      - name: Upload checkstyle artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'checkstyle-report-${{ matrix.platform }}'
          path: 'build/reports/checkstyle'

      - name: Comment on PR with artifact link
        if: github.event_name == 'pull_request' && matrix.platform == 'ubuntu-latest' && matrix.report_type == 'test-report'
        uses: actions/github-script@v6
        with:
          script: |
            const artifactLink = `https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts`
            const commentBody = `:page_facing_up: [Reports available here](${artifactLink})`
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })

      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Only deploy on push to main/master branch
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        report_type: [test-report, checkstyle-report]

    steps:
      # Create combined directory structure
      - name: Create directory structure
        run: |
          mkdir -p combined-reports/test-reports
          mkdir -p combined-reports/checkstyle-reports

      - name: Set report path
        id: set-report-path
        run: |
          if [ "${{ matrix.report_type }}" == "test-report" ]; then
            echo "report_path=combined-reports/test-reports/${{ matrix.platform }}" >> $GITHUB_ENV
          else
            echo "report_path=combined-reports/checkstyle-reports/${{ matrix.platform }}" >> $GITHUB_ENV
          fi

      # Download artifacts using matrix
      - name: Download ${{ matrix.report_type }} - ${{ matrix.platform }}
        uses: actions/download-artifact@v3
        with:
          name: '${{ matrix.report_type }}-${{ matrix.platform }}'
          path: ${{ env.report_path }}

      # Upload combined artifact (only once)
      - name: Upload combined artifact
        if: matrix.platform == 'ubuntu-latest' && matrix.report_type == 'test-report'
        uses: actions/upload-pages-artifact@v3
        with:
          path: combined-reports

      # Deploy to GitHub Pages (only once)
      - name: Deploy to GitHub Pages
        if: matrix.platform == 'ubuntu-latest' && matrix.report_type == 'test-report'
        id: deployment
        uses: actions/deploy-pages@v4
